# Generated by Django 5.2.3 on 2025-07-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pps_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_upload', models.FileField(blank=True, null=True, upload_to='tenant_passports/')),
                ('smoker', models.BooleanField(default=False)),
                ('consent_personal_data', models.BooleanField(default=False, help_text='I consent to the collection and processing of my personal data for the license agreement')),
                ('consent_share_data', models.BooleanField(default=False, help_text='I consent to the licensor sharing my data for the licensee agreement')),
                ('current_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('license_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.property')),
            ],
        ),
    ]
