# Generated by Django 5.2.5 on 2025-12-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_bookingrequest_agreement_sent_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='booking_request',
            field=models.ForeignKey(blank=True, help_text='Linked booking request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='properties.bookingrequest'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image', null=True),
        ),
    ]
