# Generated by Django 5.2.5 on 2025-12-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_booking_request_tenant_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Standard Agreement', max_length=200)),
                ('content', models.TextField(help_text='Main agreement text')),
                ('rules', models.TextField(help_text='House rules and regulations')),
                ('is_active', models.BooleanField(default=False, help_text='Only one agreement should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
