# Generated by Django 5.2.5 on 2026-01-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_agreementcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('cash', 'Cash')], default='bank', help_text='If Cash is selected, invoices will be created as Draft in Xero for manual approval.', max_length=10),
        ),
    ]
