# Generated by Django 5.2.5 on 2026-01-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='agreement_pdf',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
    ]
