# Generated by Django 5.2.3 on 2025-07-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('landlord', models.CharField(blank=True, max_length=100, null=True)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('internet', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('gas', models.BooleanField(default=False)),
                ('trash', models.BooleanField(default=False)),
                ('date_released', models.DateField(blank=True, null=True)),
                ('contract_length', models.IntegerField(default=0, help_text='Contract length in months')),
                ('property_video', models.FileField(blank=True, help_text='Optional video tour of the property', null=True, upload_to='')),
                ('maintenance', models.TextField(blank=True)),
                ('rooms', models.IntegerField(default=0)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rent_margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('actual_margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('real_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
