# Generated by Django 5.2.3 on 2025-08-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_is_available_availabilityaudit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Bed A / Top bunk', max_length=50)),
                ('size', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('QUEEN', 'Queen'), ('KING', 'King')], default='SINGLE', max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='target_type',
            field=models.CharField(choices=[('PROPERTY', 'Whole property'), ('ROOM', 'Room'), ('BED', 'Bed')], default='PROPERTY', help_text='Target of this booking (property / room / bed).', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='inventory_mode',
            field=models.CharField(choices=[('PROPERTY', 'Whole property'), ('ROOMS', 'Rooms'), ('BEDS', 'Beds in rooms')], default='PROPERTY', help_text='Booking granularity for this property.', max_length=8),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=False, help_text='When True, the property appears publicly and accepts booking requests.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('ENTIRE_APARTMENT', 'Entire apartment'), ('SHARED_APARTMENT', 'Shared apartment'), ('ENTIRE_HOUSE', 'Entire house'), ('SHARED_HOUSE', 'Shared house'), ('STUDIO', 'Studio')], default='ENTIRE_APARTMENT', help_text='What this place is (for filtering & display).', max_length=32),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='properties.bed'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Room 1', max_length=100)),
                ('is_ensuite', models.BooleanField(default=False)),
                ('bed_layout', models.CharField(choices=[('SINGLE', 'Single bed'), ('DOUBLE', 'Double bed'), ('TWIN', 'Twin (2 singles)'), ('QUEEN', 'Queen bed'), ('KING', 'King bed'), ('BUNK', 'Bunk beds'), ('DORM', 'Dorm (3+ singles)')], default='SINGLE', max_length=10)),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='People this room can sleep')),
                ('description', models.TextField(blank=True)),
                ('is_occupied', models.BooleanField(default=False, help_text='Whole room taken (or all beds taken if booking at bed level).')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_set', to='properties.property')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='properties.room'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='properties.room'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.room')),
            ],
        ),
    ]
