# Generated by Django 5.2.3 on 2025-08-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_bed_bookingrequest_target_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='size',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double')], default='SINGLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_layout',
            field=models.CharField(choices=[('SINGLE', 'Single bed'), ('DOUBLE', 'Double bed'), ('TWIN', 'Twin (2 singles)'), ('BUNK', 'Bunk beds'), ('DORM', 'Dorm (3+ singles)')], default='SINGLE', max_length=10),
        ),
    ]
