# Generated by Django 5.2.3 on 2025-08-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_bed_size_alter_room_bed_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='room',
            name='property',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='target_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='inventory_mode',
        ),
        migrations.AlterField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=False, help_text='When True, the property is visible in the public list and open for booking requests.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('WHOLE_PROPERTY', 'Whole property'), ('WHOLE_APARTMENT', 'Whole apartment'), ('STUDIO', 'Studio'), ('PRIVATE_SINGLE', 'Private single room'), ('PRIVATE_DOUBLE', 'Private double room'), ('TWIN_ROOM', 'Twin room (2 singles)'), ('TRIPLE_ROOM', 'Triple room'), ('QUAD_ROOM', 'Quad room'), ('ENSUITE_SINGLE', 'Ensuite single room'), ('ENSUITE_DOUBLE', 'Ensuite double room'), ('ENSUITE_TWIN', 'Ensuite twin room'), ('TWIN_2_BED_SINGLE', 'Single bed in twin bed room'), ('DORM_4_BED_SINGLE', 'Single bed in 4-bed dorm'), ('DORM_6_BED_SINGLE', 'Single bed in 6-bed dorm'), ('DORM_8_BED_SINGLE', 'Single bed in 8-bed dorm'), ('DORM_FEMALE_ONLY', 'Female-only dorm bed'), ('DORM_MALE_ONLY', 'Male-only dorm bed')], default='WHOLE_PROPERTY', help_text='What the guest can book here.', max_length=50),
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
