# Generated by Django 5.2.5 on 2025-11-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_bookingrequest_bed_remove_room_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='property',
        ),
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the common area (e.g., 'Kitchen', 'Living Room', 'Garden')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the common area')),
                ('property', models.ForeignKey(help_text='The property this common area belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='common_areas', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Common areas',
                'ordering': ['property', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(help_text="Name or identifier for the room (e.g., 'Room 1', 'Master Bedroom')", max_length=100)),
                ('room_type', models.CharField(choices=[('WHOLE_PROPERTY', 'Whole property'), ('WHOLE_APARTMENT', 'Whole apartment'), ('STUDIO', 'Studio'), ('PRIVATE_SINGLE', 'Private single room'), ('PRIVATE_DOUBLE', 'Private double room'), ('TWIN_ROOM', 'Twin room (2 singles)'), ('TRIPLE_ROOM', 'Triple room'), ('QUAD_ROOM', 'Quad room'), ('ENSUITE_SINGLE', 'Ensuite single room'), ('ENSUITE_DOUBLE', 'Ensuite double room'), ('ENSUITE_TWIN', 'Ensuite twin room'), ('TWIN_2_BED_SINGLE', 'Single bed in twin bed room'), ('DORM_4_BED_SINGLE', 'Single bed in 4-bed dorm'), ('DORM_6_BED_SINGLE', 'Single bed in 6-bed dorm'), ('DORM_8_BED_SINGLE', 'Single bed in 8-bed dorm'), ('DORM_FEMALE_ONLY', 'Female-only dorm bed'), ('DORM_MALE_ONLY', 'Male-only dorm bed')], default='PRIVATE_SINGLE', help_text='Type of room/accommodation', max_length=50)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly rent for this room', max_digits=10)),
                ('is_available', models.BooleanField(default=True, help_text='When True, the room is visible publicly and available for booking')),
                ('has_twin_beds', models.BooleanField(default=False, help_text='True if this room has 2 single beds (twin room setup)')),
                ('description', models.TextField(blank=True, help_text='Optional description specific to this room')),
                ('property', models.ForeignKey(help_text='The property this room belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='property_rooms', to='properties.property')),
            ],
            options={
                'ordering': ['property', 'room_name'],
                'unique_together': {('property', 'room_name')},
            },
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='room',
            field=models.ForeignKey(blank=True, help_text='The specific room being requested for booking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='properties.room'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.room')),
            ],
        ),
    ]
