# Generated by Django 5.2.5 on 2025-11-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_bookingrequest_property_commonarea_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bill_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly bill price for this room', max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price (or other price component)', max_digits=10),
        ),
    ]
