# Generated by Django 5.2.5 on 2025-11-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_room_bill_price_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='actual_margin',
        ),
        migrations.RemoveField(
            model_name='property',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='property',
            name='real_profit',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent_margin',
        ),
        migrations.AddField(
            model_name='property',
            name='prepay',
            field=models.BooleanField(default=False),
        ),
    ]
