# Generated by Django 5.2.5 on 2025-11-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_property_actual_margin_remove_property_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rent',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the specific room', null=True, upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('STUDIO', 'Studio'), ('PRIVATE_SINGLE', 'Private single room'), ('PRIVATE_DOUBLE', 'Private double room'), ('TWIN_ROOM', 'Twin room (2 singles)'), ('TRIPLE_ROOM', 'Triple room'), ('QUAD_ROOM', 'Quad room'), ('ENSUITE_SINGLE', 'Ensuite single room'), ('ENSUITE_DOUBLE', 'Ensuite double room'), ('ENSUITE_TWIN', 'Ensuite twin room'), ('TWIN_2_BED_SINGLE', 'Single bed in twin bed room'), ('DORM_4_BED_SINGLE', 'Single bed in 4-bed dorm'), ('DORM_6_BED_SINGLE', 'Single bed in 6-bed dorm'), ('DORM_8_BED_SINGLE', 'Single bed in 8-bed dorm'), ('DORM_FEMALE_ONLY', 'Female-only dorm bed'), ('DORM_MALE_ONLY', 'Male-only dorm bed')], default='PRIVATE_SINGLE', help_text='What the guest can book here.', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('STUDIO', 'Studio'), ('PRIVATE_SINGLE', 'Private single room'), ('PRIVATE_DOUBLE', 'Private double room'), ('TWIN_ROOM', 'Twin room (2 singles)'), ('TRIPLE_ROOM', 'Triple room'), ('QUAD_ROOM', 'Quad room'), ('ENSUITE_SINGLE', 'Ensuite single room'), ('ENSUITE_DOUBLE', 'Ensuite double room'), ('ENSUITE_TWIN', 'Ensuite twin room'), ('TWIN_2_BED_SINGLE', 'Single bed in twin bed room'), ('DORM_4_BED_SINGLE', 'Single bed in 4-bed dorm'), ('DORM_6_BED_SINGLE', 'Single bed in 6-bed dorm'), ('DORM_8_BED_SINGLE', 'Single bed in 8-bed dorm'), ('DORM_FEMALE_ONLY', 'Female-only dorm bed'), ('DORM_MALE_ONLY', 'Male-only dorm bed')], default='PRIVATE_SINGLE', help_text='Type of room/accommodation', max_length=50),
        ),
    ]
