# Generated by Django 5.2.5 on 2025-11-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_remove_property_rent_room_image_alter_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
    ]
