# Generated by Django 5.2.5 on 2025-12-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_remove_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='agreement_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
