# Generated by Django 5.2.5 on 2025-12-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_monthly_invoices', models.BooleanField(default=False, help_text='Automatically generate monthly invoices')),
                ('enable_auto_reconciliation', models.BooleanField(default=False, help_text='Automatically reconcile bank transactions')),
            ],
        ),
    ]
